name: Dev Branch CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  push_checks:
    if: github.event_name == 'push'
    name: Dev Push Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: |
          echo "NODE_ENV=test" >> .env.test
          echo "JWT_SECRET=test_secret" >> .env.test
          echo "NEXTAUTH_SECRET=test_secret" >> .env.test
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env.test
          echo "DATABASE_URL=mysql://root:root@localhost:3306/test_db" >> .env.test
      - env:
          CI: true
          NODE_ENV: test
          JWT_SECRET: test_secret
          NEXTAUTH_SECRET: test_secret
          NEXTAUTH_URL: http://localhost:3000
          DATABASE_URL: mysql://root:root@localhost:3306/test_db
        run: npm run test:ci

  pr_checks:
    if: github.event_name == 'pull_request'
    name: Dev PR Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: |
          echo "NODE_ENV=test" >> .env.test
          echo "JWT_SECRET=test_secret" >> .env.test
          echo "NEXTAUTH_SECRET=test_secret" >> .env.test
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env.test
          echo "DATABASE_URL=mysql://root:root@localhost:3306/test_db" >> .env.test
      - env:
          CI: true
          NODE_ENV: test
          JWT_SECRET: test_secret
          NEXTAUTH_SECRET: test_secret
          NEXTAUTH_URL: http://localhost:3000
          DATABASE_URL: mysql://root:root@localhost:3306/test_db
        run: npm run test:ci
