name: Development Branch Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # 設置 MySQL 服務
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: camp_explorer_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Create env file
      run: |
        # Database
        echo "DB_HOST=localhost" >> .env.local
        echo "DB_USER=root" >> .env.local
        echo "DB_PASSWORD=root" >> .env.local
        echo "DB_NAME=camp_explorer_db" >> .env.local
        echo "DB_PORT=3306" >> .env.local
        echo "DB_CONNECTION_LIMIT=10" >> .env.local
        echo "DB_TIMEZONE=+08:00" >> .env.local

        # URLs
        echo "NEXTAUTH_URL=http://localhost:3000" >> .env.local
        echo "NEXT_PUBLIC_API_URL=http://localhost:3002" >> .env.local
        echo "NEXT_PUBLIC_SOCKET_URL=http://localhost:3002" >> .env.local
        echo "NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000" >> .env.local
        echo "NEXT_PUBLIC_BASE_URL=http://localhost:3000" >> .env.local

        # API Keys and Secrets (從 GitHub Secrets 獲取)
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env.local
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.local
        echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.local
        echo "CWB_API_KEY=${{ secrets.CWB_API_KEY }}" >> .env.local
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.local
        echo "LINEPAY_CHANNEL_SECRET=${{ secrets.LINEPAY_CHANNEL_SECRET }}" >> .env.local
        echo "ECPAY_HASH_KEY=${{ secrets.ECPAY_HASH_KEY }}" >> .env.local
        echo "ECPAY_HASH_IV=${{ secrets.ECPAY_HASH_IV }}" >> .env.local

        # 其他配置
        echo "NODE_ENV=test" >> .env.local
        echo "GOOGLE_CLIENT_ID=1023222048385-vrsr9jg9qu4qqnal2a1guv2jmmohq2av.apps.googleusercontent.com" >> .env.local
        echo "LINEPAY_CHANNEL_ID=2006896322" >> .env.local
        echo "LINEPAY_API_URL=https://sandbox-api-pay.line.me" >> .env.local
        echo "ECPAY_MERCHANT_ID=3002607" >> .env.local
        echo "ECPAY_API_URL=https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5" >> .env.local

    - name: Install Dependencies
      run: npm ci

    - name: Lint Check
      run: npm run lint
      
    - name: Type Check Next.js
      run: npx tsc --noEmit

    - name: Run Tests
      env:
        DB_HOST: localhost
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: camp_explorer_db
        DB_PORT: 3306
        DB_CONNECTION_LIMIT: 10
        DB_TIMEZONE: +08:00
        NEXTAUTH_URL: http://localhost:3000
        NEXT_PUBLIC_API_URL: http://localhost:3002
        NEXT_PUBLIC_SOCKET_URL: http://localhost:3002
        NEXT_PUBLIC_FRONTEND_URL: http://localhost:3000
        JWT_SECRET: test_secret
        NODE_ENV: test
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: npm run test:server 