name: Development Branch Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        npm install
        npm install -g cross-env

    - name: Create env file
      run: |
        echo "NODE_ENV=test" >> .env.test
        echo "JWT_SECRET=test_secret" >> .env.test

    - name: Run Tests
      env:
        CI: true
        NODE_ENV: test
        JWT_SECRET: test_secret
      run: npm run test:ci 